In [52]:
import duckdb

con = duckdb.connect()
con.sql("CREATE VIEW t  AS SELECT * FROM '../data/raw/movimientos_dia_T.parquet'")
con.sql("CREATE VIEW t1 AS SELECT * FROM '../data/raw/movimientos_dia_T1.parquet'")

In [53]:
%load_ext sql
%sql con --alias duckdb
%config SqlMagic.displaycon = False
%config SqlMagic.displaylimit = None

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

displaylimit: Value None will be treated as 0 (no limit)

In [54]:
%%sql
SELECT * FROM t
LIMIT 10

+------------+------------+--------------------+---------+-------------------+-------------+----------------------------+-------------------+
| id_cliente |    date    |      product       |   type  |        fund       |    amount   |        description         |  commercial_name  |
+------------+------------+--------------------+---------+-------------------+-------------+----------------------------+-------------------+
| CLI001004  | 2024-09-22 | Fondo de Inversión |   out   |    Crecimiento    |  1490831.17 |       Retiro parcial       |        BBVA       |
| CLI002933  | 2024-10-05 |        ETF         |    IN   |    Crecimiento    | 37940609.55 | Comisión de administración | Fiduciaria Bogotá |
| CLI001379  | 2024-09-18 | Fondo de Inversión | entrada | Mercado Monetario |  36486859.6 | Comisión de administración |     Davivienda    |
| CLI002534  | 2024-10-13 |       Bonos        |  salida |     Renta Fija    | 49261090.81 |       Retiro parcial       |     Davivienda    |
| CLI001495  | 2024-09-20 |       Bonos        | entrada |    Conservador    | 30456941.15 |       Retiro parcial       |        Itaú       |
| CLI002622  | 2024-10-07 |  Fondo de Pensión  | entrada |   Internacional   | 40252484.99 |      Venta de activo       |        BBVA       |
| CLI002941  | 2024-09-25 |      Divisas       |  salida |    Conservador    | 12332128.76 |   Ajuste por valoración    |    BTG Pactual    |
| CLI002391  | 2024-09-27 |      Acciones      | entrada |     Renta Fija    |  7642913.13 |            None            |  Corficolombiana  |
| CLI002441  | 2024-09-29 |        CDT         |  salida |     Renta Fija    | 13341992.67 |            None            | Fiduciaria Bogotá |
| CLI001859  | 2024-09-15 |  Cuenta de Ahorro  | entrada |   Internacional   | 43526057.97 |            None            |    BTG Pactual    |
+------------+------------+--------------------+---------+-------------------+-------------+----------------------------+-------------------+

In [55]:
%%sql
DESCRIBE t

+-----------------+-------------+------+------+---------+-------+
|   column_name   | column_type | null | key  | default | extra |
+-----------------+-------------+------+------+---------+-------+
|    id_cliente   |   VARCHAR   | YES  | None |   None  |  None |
|       date      |   VARCHAR   | YES  | None |   None  |  None |
|     product     |   VARCHAR   | YES  | None |   None  |  None |
|       type      |   VARCHAR   | YES  | None |   None  |  None |
|       fund      |   VARCHAR   | YES  | None |   None  |  None |
|      amount     |    DOUBLE   | YES  | None |   None  |  None |
|   description   |   VARCHAR   | YES  | None |   None  |  None |
| commercial_name |   VARCHAR   | YES  | None |   None  |  None |
+-----------------+-------------+------+------+---------+-------+

In [56]:
%%sql
DESCRIBE t1

+-----------------+-------------+------+------+---------+-------+
|   column_name   | column_type | null | key  | default | extra |
+-----------------+-------------+------+------+---------+-------+
|    id_cliente   |   VARCHAR   | YES  | None |   None  |  None |
|       date      |   VARCHAR   | YES  | None |   None  |  None |
|     product     |   VARCHAR   | YES  | None |   None  |  None |
|       type      |   VARCHAR   | YES  | None |   None  |  None |
|       fund      |   VARCHAR   | YES  | None |   None  |  None |
|      amount     |    DOUBLE   | YES  | None |   None  |  None |
|   description   |   VARCHAR   | YES  | None |   None  |  None |
| commercial_name |   VARCHAR   | YES  | None |   None  |  None |
+-----------------+-------------+------+------+---------+-------+

In [57]:
%%sql
SELECT * FROM t LIMIT 15

+------------+------------+--------------------+---------+-------------------+-------------+----------------------------+-------------------+
| id_cliente |    date    |      product       |   type  |        fund       |    amount   |        description         |  commercial_name  |
+------------+------------+--------------------+---------+-------------------+-------------+----------------------------+-------------------+
| CLI001004  | 2024-09-22 | Fondo de Inversión |   out   |    Crecimiento    |  1490831.17 |       Retiro parcial       |        BBVA       |
| CLI002933  | 2024-10-05 |        ETF         |    IN   |    Crecimiento    | 37940609.55 | Comisión de administración | Fiduciaria Bogotá |
| CLI001379  | 2024-09-18 | Fondo de Inversión | entrada | Mercado Monetario |  36486859.6 | Comisión de administración |     Davivienda    |
| CLI002534  | 2024-10-13 |       Bonos        |  salida |     Renta Fija    | 49261090.81 |       Retiro parcial       |     Davivienda    |
| CLI001495  | 2024-09-20 |       Bonos        | entrada |    Conservador    | 30456941.15 |       Retiro parcial       |        Itaú       |
| CLI002622  | 2024-10-07 |  Fondo de Pensión  | entrada |   Internacional   | 40252484.99 |      Venta de activo       |        BBVA       |
| CLI002941  | 2024-09-25 |      Divisas       |  salida |    Conservador    | 12332128.76 |   Ajuste por valoración    |    BTG Pactual    |
| CLI002391  | 2024-09-27 |      Acciones      | entrada |     Renta Fija    |  7642913.13 |            None            |  Corficolombiana  |
| CLI002441  | 2024-09-29 |        CDT         |  salida |     Renta Fija    | 13341992.67 |            None            | Fiduciaria Bogotá |
| CLI001859  | 2024-09-15 |  Cuenta de Ahorro  | entrada |   Internacional   | 43526057.97 |            None            |    BTG Pactual    |
| CLI000662  | 2024-10-02 |        CDT         |  salida |     Balanceado    |     None    |   Traslado entre fondos    |     Scotiabank    |
| CLI002324  | 2024-10-15 |      Divisas       | entrada |   Internacional   | 32987881.39 |   Reinversión automática   |     Scotiabank    |
| CLI000868  | 2024-10-14 |       Bonos        | entrada |     Balanceado    |  21905566.1 |      Venta de activo       |        BBVA       |
| CLI002410  | 2024-10-02 |       Bonos        | entrada |     renta fija    | 42981910.38 |       Retiro parcial       |     Scotiabank    |
| CLI000542  | 2024-10-08 |      Divisas       |  salida |     Balanceado    |  4847443.78 | Comisión de administración | Fiduciaria Bogotá |
+------------+------------+--------------------+---------+-------------------+-------------+----------------------------+-------------------+

In [58]:
%%sql
SELECT COUNT(*) AS filas,
       COUNT(DISTINCT id_cliente) AS ids_distintos,
       COUNT(*) - COUNT(id_cliente) AS ids_nulos
FROM t

+-------+---------------+-----------+
| filas | ids_distintos | ids_nulos |
+-------+---------------+-----------+
| 50000 |      3000     |     0     |
+-------+---------------+-----------+

In [59]:
%%sql
SELECT count (*) FROM t

+--------------+
| count_star() |
+--------------+
|    50000     |
+--------------+

In [60]:
%%sql
SELECT count (*) FROM t1

+--------------+
| count_star() |
+--------------+
|    49000     |
+--------------+

In [61]:
%%sql
SELECT * FROM t ORDER BY id_cliente, date LIMIT 20

+------------+------------+------------------+---------+-------------------+-------------+----------------------------+---------------------+
| id_cliente |    date    |     product      |   type  |        fund       |    amount   |        description         |   commercial_name   |
+------------+------------+------------------+---------+-------------------+-------------+----------------------------+---------------------+
| CLI000001  | 2024-09-15 |     Divisas      | entrada |     Renta Fija    | 18473753.81 |   Reinversión automática   |   Corficolombiana   |
| CLI000001  | 2024-09-15 |      Bonos       | entrada |   Internacional   |  2516265.71 |   Reinversión automática   |  Fiduciaria Bogotá  |
| CLI000001  | 2024-09-17 |      Bonos       | entrada |   Internacional   |  6915867.08 |  Rendimiento del período   |         None        |
| CLI000001  | 2024-09-18 | Fondo de Pensión |  salida |   Internacional   |  1558625.61 | Comisión de administración | Valores Bancolombia |
| CLI000001  | 2024-09-18 |      Bonos       |  salida |   Internacional   | 31951275.58 |    Redención anticipada    |       Skandia       |
| CLI000001  | 2024-09-20 |       ETF        |  salida |    Conservador    | 29232177.84 |      Venta de activo       |         Itaú        |
| CLI000001  | 2024-09-24 | Fondo de Pensión |  salida |     Balanceado    | 28937945.84 |   Traslado entre fondos    |         None        |
| CLI000001  | 2024-09-27 |     Acciones     |  salida |     Renta Fija    | 41357514.56 |  Rendimiento del período   |         None        |
| CLI000001  | 2024-09-27 |     Acciones     | entrada |    conservador    |  17729533.2 |  Rendimiento del período   |   Corficolombiana   |
| CLI000001  | 2024-10-01 |       ETF        | entrada | Mercado Monetario | 46205433.83 |   Traslado entre fondos    |         BBVA        |
| CLI000001  | 2024-10-08 |     Divisas      |  salida | Mercado Monetario | 32033204.17 |   Reinversión automática   |      Davivienda     |
| CLI000001  | 2024-10-09 |     Divisas      | entrada | Mercado Monetario |  5480614.8  |      Venta de activo       |   Corficolombiana   |
| CLI000001  | 2024-10-11 |       CDT        |  salida |     Renta Fija    |  49848360.7 |  Rendimiento del período   |     BTG Pactual     |
| CLI000001  | 2024-10-12 | Cuenta de Ahorro |  salida |    Conservador    | 48632732.53 |   Ajuste por valoración    |         BBVA        |
| CLI000001  | 27/09/2024 |       CDT        |  salida | Mercado Monetario | 29981200.75 |      Compra de activo      |     BTG Pactual     |
| CLI000002  | 08/10/2024 | Cuenta de Ahorro |  salida | Mercado Monetario | 45136637.73 |      Compra de activo      |         Itaú        |
| CLI000002  | 2024-09-16 |       ETF        |  salida |     Renta Fija    |  3544574.01 |   Traslado entre fondos    | Valores Bancolombia |
| CLI000002  | 2024-09-21 |       CDT        | entrada |     Balanceado    |  3522506.94 |       Retiro parcial       |       Skandia       |
| CLI000002  | 2024-09-27 |     Acciones     |  salida |   Internacional   | 46723678.24 |   Reinversión automática   | Valores Bancolombia |
| CLI000002  | 2024-09-28 |       ETF        |    in   |   Internacional   | 13098732.31 |    Redención anticipada    |         None        |
+------------+------------+------------------+---------+-------------------+-------------+----------------------------+---------------------+

In [62]:
%%sql
SELECT
  COUNT(*) AS filas,
  COUNT(DISTINCT (id_cliente, date)) AS cliente_fecha,
  COUNT(DISTINCT (id_cliente, date, product)) AS mas_producto,
  COUNT(DISTINCT (id_cliente, date, product, fund)) AS mas_fondo,
  COUNT(DISTINCT (id_cliente, date, product, fund, type)) AS mas_tipo,
  COUNT(DISTINCT (id_cliente, date, product, fund, type, commercial_name)) AS mas_comercial,
  COUNT(DISTINCT (id_cliente, date, product, fund, type, commercial_name, amount, description)) AS fila_completa
FROM t

+-------+---------------+--------------+-----------+----------+---------------+---------------+
| filas | cliente_fecha | mas_producto | mas_fondo | mas_tipo | mas_comercial | fila_completa |
+-------+---------------+--------------+-----------+----------+---------------+---------------+
| 50000 |     40172     |    48586     |   49843   |  49933   |     49993     |     50000     |
+-------+---------------+--------------+-----------+----------+---------------+---------------+

In [63]:
%%sql
SELECT
  (SELECT COUNT(*) FROM t1) AS filas_t1,
  (SELECT COUNT(*) FROM (SELECT * FROM t INTERSECT ALL SELECT * FROM t1)) AS identicas,
  (SELECT COUNT(*) FROM (SELECT * FROM t EXCEPT ALL SELECT * FROM t1)) AS solo_en_t,
  (SELECT COUNT(*) FROM (SELECT * FROM t1 EXCEPT ALL SELECT * FROM t)) AS solo_en_t1

+----------+-----------+-----------+------------+
| filas_t1 | identicas | solo_en_t | solo_en_t1 |
+----------+-----------+-----------+------------+
|  49000   |   35159   |   14841   |   13841    |
+----------+-----------+-----------+------------+

In [64]:
%%sql
WITH solo_t AS (SELECT * FROM t EXCEPT ALL SELECT * FROM t1),
     solo_t1 AS (SELECT * FROM t1 EXCEPT ALL SELECT * FROM t)
SELECT
  COUNT(*) AS pares,
  COUNT(*) FILTER (WHERE a.amount IS DISTINCT FROM b.amount) AS cambia_amount,
  COUNT(*) FILTER (WHERE a.description IS DISTINCT FROM b.description) AS cambia_description,
  COUNT(*) FILTER (WHERE a.commercial_name IS DISTINCT FROM b.commercial_name) AS cambia_commercial
FROM solo_t a
JOIN solo_t1 b USING (id_cliente, date, product, fund, type)

+-------+---------------+--------------------+-------------------+
| pares | cambia_amount | cambia_description | cambia_commercial |
+-------+---------------+--------------------+-------------------+
|  3851 |      2350     |        1511        |         9         |
+-------+---------------+--------------------+-------------------+

In [65]:
%%sql
SELECT type, COUNT(*) AS n
FROM t
GROUP BY type
ORDER BY n DESC

+---------+-------+
|   type  |   n   |
+---------+-------+
| entrada | 25423 |
|  salida | 20631 |
|    IN   |  586  |
| Entrada |  547  |
| ENTRADA |  530  |
|    in   |  520  |
|  Salida |  478  |
|   out   |  448  |
|  SALIDA |  429  |
|   OUT   |  408  |
+---------+-------+

In [66]:
%%sql
SELECT type, COUNT(*) AS n
FROM t1
GROUP BY type
ORDER BY n DESC

+---------+-------+
|   type  |   n   |
+---------+-------+
| entrada | 24940 |
|  salida | 20187 |
|    IN   |  549  |
| Entrada |  543  |
| ENTRADA |  537  |
|    in   |  531  |
|  Salida |  457  |
|   out   |  455  |
|  SALIDA |  407  |
|   OUT   |  394  |
+---------+-------+

In [67]:
%%sql
SELECT '[' || product || ']' AS product_visible,
       COUNT(*) FILTER (WHERE origen = 'T') AS en_t,
       COUNT(*) FILTER (WHERE origen = 'T1') AS en_t1
FROM (SELECT product, 'T' AS origen FROM t
      UNION ALL
      SELECT product, 'T1' FROM t1)
GROUP BY product
ORDER BY product

+----------------------+------+-------+
|   product_visible    | en_t | en_t1 |
+----------------------+------+-------+
|      [Acciones]      | 6225 |  6079 |
|       [Bonos]        | 6222 |  6169 |
|        [CDT]         | 6333 |  6181 |
|  [Cuenta de Ahorro]  | 6343 |  6221 |
|      [Divisas]       | 6222 |  6107 |
|        [ETF]         | 6201 |  6065 |
| [Fondo de Inversión] | 6257 |  6095 |
|  [Fondo de Pensión]  | 6197 |  6083 |
+----------------------+------+-------+

In [68]:
%%sql
SELECT regexp_replace(id_cliente, '\d', '9', 'g') AS patron,
       COUNT(*) FILTER (WHERE origen = 'T') AS en_t,
       COUNT(*) FILTER (WHERE origen = 'T1') AS en_t1,
       MIN(id_cliente) AS ejemplo
FROM (SELECT id_cliente, 'T' AS origen FROM t
      UNION ALL
      SELECT id_cliente, 'T1' FROM t1)
GROUP BY patron
ORDER BY en_t DESC

+-----------+-------+-------+-----------+
|   patron  |  en_t | en_t1 |  ejemplo  |
+-----------+-------+-------+-----------+
| CLI999999 | 50000 | 49000 | CLI000001 |
+-----------+-------+-------+-----------+

In [69]:
%%sql
SELECT
  (SELECT COUNT(DISTINCT id_cliente) FROM t)  AS clientes_t,
  (SELECT COUNT(DISTINCT id_cliente) FROM t1) AS clientes_t1,
  (SELECT COUNT(*) FROM (SELECT id_cliente FROM t EXCEPT SELECT id_cliente FROM t1)) AS solo_en_t,
  (SELECT COUNT(*) FROM (SELECT id_cliente FROM t1 EXCEPT SELECT id_cliente FROM t)) AS solo_en_t1

+------------+-------------+-----------+------------+
| clientes_t | clientes_t1 | solo_en_t | solo_en_t1 |
+------------+-------------+-----------+------------+
|    3000    |     3000    |     0     |     0      |
+------------+-------------+-----------+------------+

In [70]:
%%sql
SELECT regexp_replace(date, '\d', '9', 'g') AS patron,
       COUNT(*) FILTER (WHERE origen = 'T') AS en_t,
       COUNT(*) FILTER (WHERE origen = 'T1') AS en_t1,
       MIN(date) AS ejemplo_min,
       MAX(date) AS ejemplo_max
FROM (SELECT date, 'T' AS origen FROM t
      UNION ALL
      SELECT date, 'T1' FROM t1)
GROUP BY patron
ORDER BY en_t DESC

+------------+-------+-------+-------------+-------------+
|   patron   |  en_t | en_t1 | ejemplo_min | ejemplo_max |
+------------+-------+-------+-------------+-------------+
| 9999-99-99 | 46518 | 45567 |  2024-09-15 |  2024-10-16 |
| 99/99/9999 |  3482 |  3433 |  01/10/2024 |  30/09/2024 |
+------------+-------+-------+-------------+-------------+

In [71]:
%%sql
SELECT
  MAX(CAST(split_part(date, '/', 1) AS INT)) AS max_primera_parte,
  MAX(CAST(split_part(date, '/', 2) AS INT)) AS max_segunda_parte,
  COUNT(*) AS filas
FROM (SELECT date FROM t UNION ALL SELECT date FROM t1)
WHERE date LIKE '%/%'

+-------------------+-------------------+-------+
| max_primera_parte | max_segunda_parte | filas |
+-------------------+-------------------+-------+
|         30        |         10        |  6915 |
+-------------------+-------------------+-------+

In [72]:
%%sql
WITH fechas AS (
  SELECT date AS original,
         COALESCE(try_strptime(date, '%Y-%m-%d'), try_strptime(date, '%d/%m/%Y'))::DATE AS fecha
  FROM (SELECT date FROM t UNION ALL SELECT date FROM t1)
)
SELECT
  COUNT(*) FILTER (WHERE fecha IS NULL) AS no_convertibles,
  MIN(fecha) AS fecha_min,
  MAX(fecha) AS fecha_max
FROM fechas

+-----------------+------------+------------+
| no_convertibles | fecha_min  | fecha_max  |
+-----------------+------------+------------+
|        0        | 2024-09-15 | 2024-10-16 |
+-----------------+------------+------------+

In [73]:
%%sql
SELECT '[' || fund || ']' AS fund_visible,
       COUNT(*) FILTER (WHERE origen = 'T') AS en_t,
       COUNT(*) FILTER (WHERE origen = 'T1') AS en_t1
FROM (SELECT fund, 'T' AS origen FROM t
      UNION ALL
      SELECT fund, 'T1' FROM t1)
GROUP BY fund
ORDER BY LOWER(fund)

+----------------------+------+-------+
|     fund_visible     | en_t | en_t1 |
+----------------------+------+-------+
|   [  crecimiento]    | 366  |  352  |
|    [  Renta Fija]    | 367  |  354  |
| [  Renta Variable  ] | 392  |  404  |
|     [BALANCEADO]     | 398  |  398  |
|     [Balanceado]     | 6254 |  6060 |
|     [balanceado]     | 359  |  367  |
|    [Conservador]     | 6275 |  6177 |
|    [conservador]     | 377  |  366  |
|    [Conservador ]    | 358  |  368  |
|    [Crecimiento]     | 6352 |  6212 |
|    [crecimiento]     | 384  |  363  |
|   [Internacional]    | 6385 |  6217 |
|   [internacional]    | 365  |  368  |
|   [INTERNACIONAL]    | 388  |  361  |
| [Mercado  Monetario] | 352  |  345  |
| [Mercado Monetario]  | 6237 |  6159 |
| [mercado monetario]  | 395  |  384  |
|     [Renta Fija]     | 6263 |  6170 |
|     [renta fija]     | 387  |  350  |
|     [RENTA FIJA]     | 372  |  387  |
|   [Renta Variable]   | 6245 |  6105 |
|   [RENTA VARIABLE]   | 347  |  356  |
|   [renta variable]   | 382  |  377  |
+----------------------+------+-------+

In [74]:
%%sql
SELECT '[' || LOWER(TRIM(fund)) || ']' AS fund_limpio,
       COUNT(*) AS n
FROM (SELECT fund FROM t UNION ALL SELECT fund FROM t1)
GROUP BY fund_limpio
ORDER BY fund_limpio

+----------------------+-------+
|     fund_limpio      |   n   |
+----------------------+-------+
|     [balanceado]     | 13836 |
|    [conservador]     | 13921 |
|    [crecimiento]     | 14029 |
|   [internacional]    | 14084 |
| [mercado  monetario] |  697  |
| [mercado monetario]  | 13175 |
|     [renta fija]     | 14650 |
|   [renta variable]   | 14608 |
+----------------------+-------+

In [75]:
%%sql
SELECT DISTINCT
  '[' || fund || ']' AS visible,
  LENGTH(fund) AS largo,
  encode(fund) AS bytes
FROM (SELECT fund FROM t UNION ALL SELECT fund FROM t1)
WHERE LOWER(fund) LIKE '%mercado%'

+----------------------+-------+-----------------------+
|       visible        | largo |         bytes         |
+----------------------+-------+-----------------------+
| [mercado monetario]  |   17  |  b'mercado monetario' |
| [Mercado Monetario]  |   17  |  b'Mercado Monetario' |
| [Mercado  Monetario] |   18  | b'Mercado  Monetario' |
+----------------------+-------+-----------------------+

In [76]:
%%sql
SELECT DISTINCT
  LENGTH(fund) AS largo,
  unicode(right(fund, 1)) AS codigo_ultimo,
  unicode(left(fund, 1)) AS codigo_primero
FROM (SELECT fund FROM t UNION ALL SELECT fund FROM t1)
WHERE LOWER(fund) LIKE '%mercado%'

+-------+---------------+----------------+
| largo | codigo_ultimo | codigo_primero |
+-------+---------------+----------------+
|   18  |      111      |       77       |
|   17  |      111      |       77       |
|   17  |      111      |      109       |
+-------+---------------+----------------+

In [77]:
%%sql
SELECT DISTINCT
  LENGTH(fund) AS largo,
  unicode(substr(fund, 8, 1)) AS pos_8,
  unicode(substr(fund, 9, 1)) AS pos_9,
  unicode(substr(fund, 10, 1)) AS pos_10
FROM (SELECT fund FROM t UNION ALL SELECT fund FROM t1)
WHERE LOWER(fund) LIKE '%mercado%'

+-------+-------+-------+--------+
| largo | pos_8 | pos_9 | pos_10 |
+-------+-------+-------+--------+
|   18  |   32  |   32  |   77   |
|   17  |   32  |   77  |  111   |
|   17  |   32  |  109  |  111   |
+-------+-------+-------+--------+

In [78]:
%%sql
SELECT '[' || LOWER(TRIM(regexp_replace(fund, '\s+', ' ', 'g'))) || ']' AS fund_limpio,
       COUNT(*) AS n
FROM (SELECT fund FROM t UNION ALL SELECT fund FROM t1)
GROUP BY fund_limpio
ORDER BY fund_limpio

+---------------------+-------+
|     fund_limpio     |   n   |
+---------------------+-------+
|     [balanceado]    | 13836 |
|    [conservador]    | 13921 |
|    [crecimiento]    | 14029 |
|   [internacional]   | 14084 |
| [mercado monetario] | 13872 |
|     [renta fija]    | 14650 |
|   [renta variable]  | 14608 |
+---------------------+-------+

In [79]:
%%sql
SELECT LOWER(TRIM(regexp_replace(description, '\s+', ' ', 'g'))) AS desc_limpia,
       COUNT(DISTINCT description) AS variantes_crudas,
       COUNT(*) FILTER (WHERE origen = 'T') AS en_t,
       COUNT(*) FILTER (WHERE origen = 'T1') AS en_t1
FROM (SELECT description, 'T' AS origen FROM t
      UNION ALL
      SELECT description, 'T1' FROM t1)
GROUP BY desc_limpia
ORDER BY desc_limpia

+----------------------------+------------------+------+-------+
|        desc_limpia         | variantes_crudas | en_t | en_t1 |
+----------------------------+------------------+------+-------+
|   ajuste por valoración    |        1         | 4514 |  4452 |
| comisión de administración |        1         | 4621 |  4488 |
|      compra de activo      |        1         | 4453 |  4322 |
|      depósito inicial      |        1         | 4474 |  4420 |
|    redención anticipada    |        1         | 4524 |  4497 |
|   reinversión automática   |        1         | 4574 |  4490 |
|  rendimiento del período   |        1         | 4499 |  4380 |
|       retiro parcial       |        1         | 4540 |  4429 |
|   traslado entre fondos    |        1         | 4605 |  4503 |
|      venta de activo       |        1         | 4633 |  4534 |
|            None            |        0         | 4563 |  4485 |
+----------------------------+------------------+------+-------+

In [80]:
%%sql
SELECT description,
       COUNT(*) FILTER (WHERE LOWER(TRIM(type)) IN ('entrada','in')) AS entradas,
       COUNT(*) FILTER (WHERE LOWER(TRIM(type)) IN ('salida','out')) AS salidas
FROM (SELECT description, type FROM t UNION ALL SELECT description, type FROM t1)
GROUP BY description
ORDER BY description

+----------------------------+----------+---------+
|        description         | entradas | salidas |
+----------------------------+----------+---------+
|   Ajuste por valoración    |   4904   |   4062  |
| Comisión de administración |   4915   |   4194  |
|      Compra de activo      |   4836   |   3939  |
|      Depósito inicial      |   4852   |   4042  |
|    Redención anticipada    |   5041   |   3980  |
|   Reinversión automática   |   5054   |   4010  |
|  Rendimiento del período   |   4973   |   3906  |
|       Retiro parcial       |   4970   |   3999  |
|   Traslado entre fondos    |   5048   |   4060  |
|      Venta de activo       |   5070   |   4097  |
|            None            |   5043   |   4005  |
+----------------------------+----------+---------+

In [81]:
%%sql
SELECT description,
       COUNT(*) FILTER (WHERE LOWER(TRIM(type)) IN ('entrada','in')) AS entradas,
       COUNT(*) FILTER (WHERE LOWER(TRIM(type)) IN ('salida','out')) AS salidas
FROM (SELECT description, type FROM t UNION ALL SELECT description, type FROM t1)
GROUP BY description
ORDER BY description

+----------------------------+----------+---------+
|        description         | entradas | salidas |
+----------------------------+----------+---------+
|   Ajuste por valoración    |   4904   |   4062  |
| Comisión de administración |   4915   |   4194  |
|      Compra de activo      |   4836   |   3939  |
|      Depósito inicial      |   4852   |   4042  |
|    Redención anticipada    |   5041   |   3980  |
|   Reinversión automática   |   5054   |   4010  |
|  Rendimiento del período   |   4973   |   3906  |
|       Retiro parcial       |   4970   |   3999  |
|   Traslado entre fondos    |   5048   |   4060  |
|      Venta de activo       |   5070   |   4097  |
|            None            |   5043   |   4005  |
+----------------------------+----------+---------+

In [82]:
%%sql
SELECT '[' || commercial_name || ']' AS cn_visible,
       COUNT(*) FILTER (WHERE origen = 'T') AS en_t,
       COUNT(*) FILTER (WHERE origen = 'T1') AS en_t1
FROM (SELECT commercial_name, 'T' AS origen FROM t
      UNION ALL
      SELECT commercial_name, 'T1' FROM t1)
GROUP BY commercial_name
ORDER BY LOWER(commercial_name)

+-----------------------+------+-------+
|       cn_visible      | en_t | en_t1 |
+-----------------------+------+-------+
|     [Bancolombia]     | 4195 |  4071 |
|         [BBVA]        | 4181 |  4071 |
|     [BTG Pactual]     | 4066 |  3967 |
|   [Corficolombiana]   | 4136 |  4061 |
|      [Davivienda]     | 4208 |  4148 |
|  [Fiduciaria Bogotá]  | 4081 |  3990 |
|         [Itaú]        | 4150 |  4105 |
|      [Scotiabank]     | 4282 |  4196 |
|       [Skandia]       | 4158 |  4067 |
| [Valores Bancolombia] | 4236 |  4157 |
|          None         | 8307 |  8167 |
+-----------------------+------+-------+

In [83]:
%%sql
SELECT
  origen,
  COUNT(*) AS filas,
  COUNT(*) - COUNT(amount) AS nulos,
  COUNT(*) FILTER (WHERE amount < 0) AS negativos,
  COUNT(*) FILTER (WHERE amount = 0) AS ceros,
  MIN(amount) AS minimo,
  MAX(amount) AS maximo,
  ROUND(AVG(amount), 2) AS promedio,
  ROUND(MEDIAN(amount), 2) AS mediana,
  COUNT(*) FILTER (WHERE amount <> ROUND(amount, 2)) AS mas_de_2_decimales
FROM (SELECT amount, 'T' AS origen FROM t UNION ALL SELECT amount, 'T1' FROM t1)
GROUP BY origen

+--------+-------+-------+-----------+-------+--------------+-------------+-------------+-------------+--------------------+
| origen | filas | nulos | negativos | ceros |    minimo    |    maximo   |   promedio  |   mediana   | mas_de_2_decimales |
+--------+-------+-------+-----------+-------+--------------+-------------+-------------+-------------+--------------------+
|   T    | 50000 |  1543 |    1034   |  940  | -49905610.23 | 49998466.14 | 23389951.27 | 23884861.99 |         0          |
|   T1   | 49000 |  1440 |    989    |  903  | -49905610.23 | 49998466.14 | 23408449.16 | 23884058.63 |         0          |
+--------+-------+-------+-----------+-------+--------------+-------------+-------------+-------------+--------------------+

In [104]:
%%sql
SELECT
  CASE WHEN LOWER(TRIM(type)) IN ('entrada','in') THEN 'entrada' ELSE 'salida' END AS type_limpio,
  COUNT(*) FILTER (WHERE amount < 0) AS negativos,
  COUNT(*) FILTER (WHERE amount > 0) AS positivos
FROM (SELECT type, amount FROM t UNION ALL SELECT type, amount FROM t1)
GROUP BY type_limpio

+-------------+-----------+-----------+
| type_limpio | negativos | positivos |
+-------------+-----------+-----------+
|   entrada   |    2023   |   50009   |
|    salida   |     0     |   42142   |
+-------------+-----------+-----------+

In [115]:
%%sql
SELECT *,
  CASE WHEN LOWER(TRIM(type)) IN ('entrada','in') THEN 'entrada' ELSE 'salida' END AS type_limpio
FROM  t
WHERE id_cliente = 'CLI002818' 
ORDER BY date

+------------+------------+--------------------+---------+-------------------+--------------+----------------------------+---------------------+-------------+
| id_cliente |    date    |      product       |   type  |        fund       |    amount    |        description         |   commercial_name   | type_limpio |
+------------+------------+--------------------+---------+-------------------+--------------+----------------------------+---------------------+-------------+
| CLI002818  | 17/09/2024 | Fondo de Inversión | entrada |    Conservador    |  33612395.6  |  Rendimiento del período   |       Skandia       |   entrada   |
| CLI002818  | 2024-09-15 |        CDT         |  salida |   Internacional   | 32517950.78  | Comisión de administración |       Skandia       |    salida   |
| CLI002818  | 2024-09-16 |        CDT         | entrada | Mercado Monetario |  21529568.9  |      Venta de activo       |         None        |   entrada   |
| CLI002818  | 2024-09-18 |        CDT         | entrada |   renta variable  | 38020183.74  |   Traslado entre fondos    |      Scotiabank     |   entrada   |
| CLI002818  | 2024-09-21 |        CDT         |  salida |     Balanceado    |  9257594.19  |       Retiro parcial       |   Corficolombiana   |    salida   |
| CLI002818  | 2024-09-21 |        ETF         | entrada |     Balanceado    | 21903604.79  |   Reinversión automática   |         None        |   entrada   |
| CLI002818  | 2024-09-22 |       Bonos        | entrada |    Crecimiento    | 28334846.85  |    Redención anticipada    |   Corficolombiana   |   entrada   |
| CLI002818  | 2024-09-23 | Fondo de Inversión | entrada | Mercado Monetario | 40263151.71  |   Ajuste por valoración    | Valores Bancolombia |   entrada   |
| CLI002818  | 2024-09-25 |        ETF         | entrada |   Internacional   | 47337612.95  |   Traslado entre fondos    |         None        |   entrada   |
| CLI002818  | 2024-10-02 |      Divisas       | entrada |   Renta Variable  | 24908809.26  |   Traslado entre fondos    |         None        |   entrada   |
| CLI002818  | 2024-10-04 |  Cuenta de Ahorro  |  salida |   Renta Variable  |  4103946.91  |  Rendimiento del período   |       Skandia       |    salida   |
| CLI002818  | 2024-10-06 |      Acciones      |  salida |    Crecimiento    | 31656747.08  | Comisión de administración |     Bancolombia     |    salida   |
| CLI002818  | 2024-10-07 |        ETF         | entrada |   Renta Variable  | 36911666.59  |      Depósito inicial      |     BTG Pactual     |   entrada   |
| CLI002818  | 2024-10-07 |       Bonos        | entrada |   Internacional   |  8580896.22  | Comisión de administración |     BTG Pactual     |   entrada   |
| CLI002818  | 2024-10-12 | Fondo de Inversión | entrada |    Crecimiento    | 29271102.73  |      Depósito inicial      |   Corficolombiana   |   entrada   |
| CLI002818  | 2024-10-14 |      Divisas       | entrada |   Internacional   | -11561538.46 |   Traslado entre fondos    |         BBVA        |   entrada   |
| CLI002818  | 2024-10-15 |       Bonos        | entrada | Mercado Monetario | 35211738.64  |   Traslado entre fondos    |         Itaú        |   entrada   |
| CLI002818  | 2024-10-15 |      Acciones      | entrada |     Renta Fija    | 24994380.28  |   Traslado entre fondos    |       Skandia       |   entrada   |
+------------+------------+--------------------+---------+-------------------+--------------+----------------------------+---------------------+-------------+

In [117]:
%%sql
SELECT *,
  CASE WHEN LOWER(TRIM(type)) IN ('entrada','in') THEN 'entrada' ELSE 'salida' END AS type_limpio
FROM  t
WHERE amount IS NULL 
ORDER BY date
LIMIT 10

+------------+------------+--------------------+---------+-------------------+--------+-----------------------+---------------------+-------------+
| id_cliente |    date    |      product       |   type  |        fund       | amount |      description      |   commercial_name   | type_limpio |
+------------+------------+--------------------+---------+-------------------+--------+-----------------------+---------------------+-------------+
| CLI001937  | 01/10/2024 | Fondo de Inversión |  salida |   internacional   |  None  |          None         |         None        |    salida   |
| CLI000970  | 01/10/2024 |       Bonos        | entrada | Mercado Monetario |  None  |     Retiro parcial    |         Itaú        |   entrada   |
| CLI000072  | 01/10/2024 | Fondo de Inversión | entrada |    Crecimiento    |  None  |          None         |     Bancolombia     |   entrada   |
| CLI000181  | 01/10/2024 |  Fondo de Pensión  | entrada |     Balanceado    |  None  |          None         |  Fiduciaria Bogotá  |   entrada   |
| CLI002237  | 02/10/2024 |        CDT         |  salida |    Crecimiento    |  None  |    Venta de activo    | Valores Bancolombia |    salida   |
| CLI002214  | 02/10/2024 |  Cuenta de Ahorro  | entrada |   Renta Variable  |  None  |    Compra de activo   |         None        |   entrada   |
| CLI000950  | 02/10/2024 | Fondo de Inversión |  salida |     Balanceado    |  None  | Ajuste por valoración |      Scotiabank     |    salida   |
| CLI002372  | 02/10/2024 |        ETF         |  salida |    Crecimiento    |  None  |     Retiro parcial    |     BTG Pactual     |    salida   |
| CLI002058  | 02/10/2024 |        ETF         |  salida |    Crecimiento    |  None  |     Retiro parcial    |     Bancolombia     |    salida   |
| CLI001642  | 03/10/2024 |  Fondo de Pensión  | entrada |    Conservador    |  None  |    Compra de activo   |         Itaú        |   entrada   |
+------------+------------+--------------------+---------+-------------------+--------+-----------------------+---------------------+-------------+

In [114]:
%%sql
SELECT *,
  CASE WHEN LOWER(TRIM(type)) IN ('entrada','in') THEN 'entrada' ELSE 'salida' END AS type_limpio
FROM  t1
WHERE id_cliente = 'CLI002818' AND description='Traslado entre fondos'
ORDER BY date

+------------+------------+----------+---------+-------------------+--------------+-----------------------+-----------------+-------------+
| id_cliente |    date    | product  |   type  |        fund       |    amount    |      description      | commercial_name | type_limpio |
+------------+------------+----------+---------+-------------------+--------------+-----------------------+-----------------+-------------+
| CLI002818  | 2024-09-18 |   CDT    | entrada |   renta variable  | 38020183.74  | Traslado entre fondos |    Scotiabank   |   entrada   |
| CLI002818  | 2024-10-14 | Divisas  | entrada |   Internacional   | -11561538.46 | Traslado entre fondos |       BBVA      |   entrada   |
| CLI002818  | 2024-10-15 |  Bonos   | entrada | Mercado Monetario | 35211738.64  | Traslado entre fondos |       Itaú      |   entrada   |
| CLI002818  | 2024-10-15 | Acciones | entrada |     Renta Fija    | 24994380.28  | Traslado entre fondos |     Skandia     |   entrada   |
+------------+------------+----------+---------+-------------------+--------------+-----------------------+-----------------+-------------+

In [86]:
import sys
import polars as pl
sys.path.append("../src")

from pathlib import Path
from etl.extraccion import listar_cortes, leer_corte

cortes = listar_cortes(Path("../data/raw"))
cortes

[(0, WindowsPath('../data/raw/movimientos_dia_T.parquet')),
 (1, WindowsPath('../data/raw/movimientos_dia_T1.parquet'))]

In [87]:
lf = leer_corte(cortes[0][1])
lf.head(5).collect()

shape: (5, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬──────────┬────────────┬────────────┐
│ id_cliente ┆ date       ┆ product    ┆ type    ┆ fund       ┆ amount   ┆ descriptio ┆ commercial │
│ ---        ┆ ---        ┆ ---        ┆ ---     ┆ ---        ┆ ---      ┆ n          ┆ _name      │
│ str        ┆ str        ┆ str        ┆ str     ┆ str        ┆ f64      ┆ ---        ┆ ---        │
│            ┆            ┆            ┆         ┆            ┆          ┆ str        ┆ str        │
╞════════════╪════════════╪════════════╪═════════╪════════════╪══════════╪════════════╪════════════╡
│ CLI001004  ┆ 2024-09-22 ┆ Fondo de   ┆ out     ┆ Crecimient ┆ 1.4908e6 ┆ Retiro     ┆ BBVA       │
│            ┆            ┆ Inversión  ┆         ┆ o          ┆          ┆ parcial    ┆            │
│ CLI002933  ┆ 2024-10-05 ┆ ETF        ┆ IN      ┆ Crecimient ┆ 3.7941e7 ┆ Comisión   ┆ Fiduciaria │
│            ┆            ┆            ┆         ┆ o          ┆          ┆ de adminis ┆ Bogotá     │
│            ┆            ┆            ┆         ┆            ┆          ┆ tración    ┆            │
│ CLI001379  ┆ 2024-09-18 ┆ Fondo de   ┆ entrada ┆ Mercado    ┆ 3.6487e7 ┆ Comisión   ┆ Davivienda │
│            ┆            ┆ Inversión  ┆         ┆ Monetario  ┆          ┆ de adminis ┆            │
│            ┆            ┆            ┆         ┆            ┆          ┆ tración    ┆            │
│ CLI002534  ┆ 2024-10-13 ┆ Bonos      ┆ salida  ┆ Renta Fija ┆ 4.9261e7 ┆ Retiro     ┆ Davivienda │
│            ┆            ┆            ┆         ┆            ┆          ┆ parcial    ┆            │
│ CLI001495  ┆ 2024-09-20 ┆ Bonos      ┆ entrada ┆ Conservado ┆ 3.0457e7 ┆ Retiro     ┆ Itaú       │
│            ┆            ┆            ┆         ┆ r          ┆          ┆ parcial    ┆            │
└────────────┴────────────┴────────────┴─────────┴────────────┴──────────┴────────────┴────────────┘

In [88]:
import sys
sys.path.append("../src")

from pathlib import Path
from etl.extraccion import listar_cortes, leer_corte
from etl.transformacion import normalizar

cortes = listar_cortes(Path("../data/raw"))
df = normalizar(leer_corte(cortes[0][1])).collect()

In [89]:
df.group_by("_fund").len().sort("_fund")

shape: (7, 2)
┌───────────────────┬──────┐
│ _fund             ┆ len  │
│ ---               ┆ ---  │
│ str               ┆ u32  │
╞═══════════════════╪══════╡
│ Balanceado        ┆ 7011 │
│ Conservador       ┆ 7010 │
│ Crecimiento       ┆ 7102 │
│ Internacional     ┆ 7138 │
│ Mercado Monetario ┆ 6984 │
│ Renta Fija        ┆ 7389 │
│ Renta Variable    ┆ 7366 │
└───────────────────┴──────┘

In [90]:
df.group_by("_type").len()

shape: (2, 2)
┌─────────┬───────┐
│ _type   ┆ len   │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
│ salida  ┆ 22394 │
│ entrada ┆ 27606 │
└─────────┴───────┘

In [91]:
df.select(
    pl.col("_date").null_count().alias("nulos"),
    pl.col("_date").min().alias("minima"),
    pl.col("_date").max().alias("maxima"),
)

shape: (1, 3)
┌───────┬────────────┬────────────┐
│ nulos ┆ minima     ┆ maxima     │
│ ---   ┆ ---        ┆ ---        │
│ u32   ┆ date       ┆ date       │
╞═══════╪════════════╪════════════╡
│ 0     ┆ 2024-09-15 ┆ 2024-10-15 │
└───────┴────────────┴────────────┘

In [92]:
from etl.transformacion import normalizar, validar

In [93]:
lf = normalizar(leer_corte(cortes[0][1]))
validos, rechazados = pl.collect_all(validar(lf))
print(f"válidos: {validos.height} | rechazados: {rechazados.height}")

válidos: 47423 | rechazados: 2577

In [94]:
rechazados.group_by("motivo").len().sort("len", descending=True)

shape: (2, 2)
┌─────────────────┬──────┐
│ motivo          ┆ len  │
│ ---             ┆ ---  │
│ str             ┆ u32  │
╞═════════════════╪══════╡
│ amount_nulo     ┆ 1543 │
│ amount_negativo ┆ 1034 │
└─────────────────┴──────┘

In [95]:
llave = ["id_cliente", "date", "product", "fund", "type"]

def limpio(i):
    validos, _ = pl.collect_all(validar(normalizar(leer_corte(cortes[i][1]))))
    return validos

t, t1 = limpio(0), limpio(1)

print("Filas con llave repetida:")
print("  T: ", t.height - t.select(llave).n_unique())
print("  T1:", t1.height - t1.select(llave).n_unique())

solo_t = t.join(t1, on=t.columns, how="anti", nulls_equal=True)
solo_t1 = t1.join(t, on=t.columns, how="anti", nulls_equal=True)
pares = solo_t.join(solo_t1, on=llave, how="inner")

print(f"\nIdénticas: {t.height - solo_t.height}")
print(f"Cambiaron en T: {solo_t.height} | en T1: {solo_t1.height}")
print(f"Emparejadas por llave (filas del join): {pares.height}")
print(f"Llaves distintas emparejadas: {pares.select(llave).n_unique()}")
print(f"Sin pareja en T (eliminadas): {solo_t.height - pares.height}")
print(f"Sin pareja en T1 (nuevas): {solo_t1.height - pares.height}")

Filas con llave repetida:
  T:  107
  T1: 98

Idénticas: 33372
Cambiaron en T: 14051 | en T1: 13199
Emparejadas por llave (filas del join): 3604
Llaves distintas emparejadas: 3600
Sin pareja en T (eliminadas): 10447
Sin pareja en T1 (nuevas): 9595

In [96]:
sin_t = solo_t.join(solo_t1, on=llave, how="anti")
sin_t1 = solo_t1.join(solo_t, on=llave, how="anti")

cruce = sin_t.join(sin_t1, on=["id_cliente", "amount"], how="inner", suffix="_t1")
print(f"Sin pareja en T: {sin_t.height} | en T1: {sin_t1.height}")
print(f"Emparejadas por cliente + monto: {cruce.height}")

columnas = ["date", "product", "fund", "type", "description", "commercial_name"]
cruce.select([pl.col(c).ne_missing(pl.col(f"{c}_t1")).sum().alias(c) for c in columnas])

Sin pareja en T: 10450 | en T1: 9596
Emparejadas por cliente + monto: 12

shape: (1, 6)
┌──────┬─────────┬──────┬──────┬─────────────┬─────────────────┐
│ date ┆ product ┆ fund ┆ type ┆ description ┆ commercial_name │
│ ---  ┆ ---     ┆ ---  ┆ ---  ┆ ---         ┆ ---             │
│ u32  ┆ u32     ┆ u32  ┆ u32  ┆ u32         ┆ u32             │
╞══════╪═════════╪══════╪══════╪═════════════╪═════════════════╡
│ 12   ┆ 12      ┆ 9    ┆ 4    ┆ 11          ┆ 9               │
└──────┴─────────┴──────┴──────┴─────────────┴─────────────────┘

In [97]:
print("Duplicados exactos tras normalizar:")
print("  T: ", t.height - t.n_unique())
print("  T1:", t1.height - t1.n_unique())

colisiones = t.filter(pl.struct(llave).is_duplicated()).sort(llave)
colisiones.head(10)

Duplicados exactos tras normalizar:
  T:  0
  T1: 0

shape: (10, 8)
┌────────────┬────────────┬────────────┬─────────┬────────────┬───────────┬────────────┬───────────┐
│ id_cliente ┆ date       ┆ product    ┆ type    ┆ fund       ┆ amount    ┆ descriptio ┆ commercia │
│ ---        ┆ ---        ┆ ---        ┆ ---     ┆ ---        ┆ ---       ┆ n          ┆ l_name    │
│ str        ┆ date       ┆ str        ┆ str     ┆ str        ┆ f64       ┆ ---        ┆ ---       │
│            ┆            ┆            ┆         ┆            ┆           ┆ str        ┆ str       │
╞════════════╪════════════╪════════════╪═════════╪════════════╪═══════════╪════════════╪═══════════╡
│ CLI000016  ┆ 2024-09-23 ┆ Divisas    ┆ entrada ┆ Renta Fija ┆ 2.9636e7  ┆ Ajuste por ┆ Skandia   │
│            ┆            ┆            ┆         ┆            ┆           ┆ valoración ┆           │
│ CLI000016  ┆ 2024-09-23 ┆ Divisas    ┆ entrada ┆ Renta Fija ┆ 4.3313e7  ┆ Ajuste por ┆ null      │
│            ┆            ┆            ┆         ┆            ┆           ┆ valoración ┆           │
│ CLI000023  ┆ 2024-10-06 ┆ Fondo de   ┆ salida  ┆ Crecimient ┆ 2.7027e7  ┆ Traslado   ┆ BBVA      │
│            ┆            ┆ Pensión    ┆         ┆ o          ┆           ┆ entre      ┆           │
│            ┆            ┆            ┆         ┆            ┆           ┆ fondos     ┆           │
│ CLI000023  ┆ 2024-10-06 ┆ Fondo de   ┆ salida  ┆ Crecimient ┆ 1.4011e7  ┆ Ajuste por ┆ Valores   │
│            ┆            ┆ Pensión    ┆         ┆ o          ┆           ┆ valoración ┆ Bancolomb │
│            ┆            ┆            ┆         ┆            ┆           ┆            ┆ ia        │
│ CLI000050  ┆ 2024-09-15 ┆ Fondo de   ┆ salida  ┆ Renta      ┆ 3.1167e7  ┆ Depósito   ┆ Itaú      │
│            ┆            ┆ Pensión    ┆         ┆ Variable   ┆           ┆ inicial    ┆           │
│ CLI000050  ┆ 2024-09-15 ┆ Fondo de   ┆ salida  ┆ Renta      ┆ 253636.61 ┆ Rendimient ┆ Fiduciari │
│            ┆            ┆ Pensión    ┆         ┆ Variable   ┆           ┆ o del      ┆ a Bogotá  │
│            ┆            ┆            ┆         ┆            ┆           ┆ período    ┆           │
│ CLI000086  ┆ 2024-10-11 ┆ Fondo de   ┆ entrada ┆ Conservado ┆ 2.6892e7  ┆ Rendimient ┆ Skandia   │
│            ┆            ┆ Pensión    ┆         ┆ r          ┆           ┆ o del      ┆           │
│            ┆            ┆            ┆         ┆            ┆           ┆ período    ┆           │
│ CLI000086  ┆ 2024-10-11 ┆ Fondo de   ┆ entrada ┆ Conservado ┆ 3.7287e7  ┆ Venta de   ┆ null      │
│            ┆            ┆ Pensión    ┆         ┆ r          ┆           ┆ activo     ┆           │
│ CLI000128  ┆ 2024-09-28 ┆ Fondo de   ┆ salida  ┆ Mercado    ┆ 1.2678e7  ┆ Reinversió ┆ null      │
│            ┆            ┆ Pensión    ┆         ┆ Monetario  ┆           ┆ n          ┆           │
│            ┆            ┆            ┆         ┆            ┆           ┆ automática ┆           │
│ CLI000128  ┆ 2024-09-28 ┆ Fondo de   ┆ salida  ┆ Mercado    ┆ 4.1144e7  ┆ Retiro     ┆ BBVA      │
│            ┆            ┆ Pensión    ┆         ┆ Monetario  ┆           ┆ parcial    ┆           │
└────────────┴────────────┴────────────┴─────────┴────────────┴───────────┴────────────┴───────────┘

In [98]:
from etl.transformacion import normalizar, validar, identificar, LLAVE

validos, _ = pl.collect_all(validar(normalizar(leer_corte(cortes[0][1]))))
ident = identificar(validos.lazy()).collect()

ident.group_by("secuencia").len().sort("secuencia")

shape: (2, 2)
┌───────────┬───────┐
│ secuencia ┆ len   │
│ ---       ┆ ---   │
│ i32       ┆ u32   │
╞═══════════╪═══════╡
│ 1         ┆ 47316 │
│ 2         ┆ 107   │
└───────────┴───────┘

In [99]:
print(ident.height == ident.select([*LLAVE, "secuencia"]).n_unique())

True

In [100]:
import sys
sys.path.append("../src")

from pathlib import Path
import polars as pl

In [101]:
from db import conectar
from etl.extraccion import listar_cortes, leer_corte
from etl.transformacion import normalizar, validar, identificar
from etl.carga import cargar_staging, registrar_rechazados

cortes = listar_cortes(Path("../data/raw"))
orden, archivo = cortes[0]

validos, rechazados = pl.collect_all(validar(normalizar(leer_corte(archivo))))
validos = identificar(validos.lazy()).collect()

conn = conectar()
cargar_staging(conn, validos, rechazados)
registrar_rechazados(conn, rechazados, archivo.name)

for tabla in ["stg_movimientos", "stg_llaves_rechazadas", "movimientos_rechazados"]:
    print(tabla, conn.execute(f"SELECT COUNT(*) FROM {tabla}").fetchone()[0])

conn.rollback()
conn.close()

stg_movimientos 47423
stg_llaves_rechazadas 2576
movimientos_rechazados 7583

In [102]:
from etl.carga import cargar_staging, registrar_rechazados, consolidar

def procesar(conn, orden, archivo):
    validos, rechazados = pl.collect_all(validar(normalizar(leer_corte(archivo))))
    validos = identificar(validos.lazy()).collect()
    cargar_staging(conn, validos, rechazados)
    return consolidar(conn, orden)

conn = conectar()
for orden, archivo in cortes:
    print(archivo.name, procesar(conn, orden, archivo))

print(conn.execute("SELECT COUNT(*) FROM movimientos_actual").fetchone()[0])
conn.rollback()
conn.close()

movimientos_dia_T.parquet {'sin_cambios': 33374, 'corregido': 3634, 'protegido': 123, 'nuevo': 10415, 'eliminado': 9476}
movimientos_dia_T1.parquet {'sin_cambios': 33461, 'corregido': 3634, 'protegido': 36, 'nuevo': 9476, 'eliminado': 10415}
46607